// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfIalkG8mwgPqI4OqgKqEBzPBI-U_5yoU',
    appId: '1:468087905702:web:339e99af72e529bde54367',
    messagingSenderId: '468087905702',
    projectId: 'chat-app-fa80b',
    authDomain: 'chat-app-fa80b.firebaseapp.com',
    storageBucket: 'chat-app-fa80b.appspot.com',
    measurementId: 'G-YP39KPZT7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF-w2xLfKUexEms1uEDYbE1gW83ho5bq4',
    appId: '1:468087905702:android:8870ee63ea225a54e54367',
    messagingSenderId: '468087905702',
    projectId: 'chat-app-fa80b',
    storageBucket: 'chat-app-fa80b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk68pQXYAyQgowVKqjpQfZLAKZoVeQf0E',
    appId: '1:468087905702:ios:bf672d174304d137e54367',
    messagingSenderId: '468087905702',
    projectId: 'chat-app-fa80b',
    storageBucket: 'chat-app-fa80b.appspot.com',
    iosClientId: '468087905702-k0qu642gvab68iru5j3oal398nlnasah.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk68pQXYAyQgowVKqjpQfZLAKZoVeQf0E',
    appId: '1:468087905702:ios:bf672d174304d137e54367',
    messagingSenderId: '468087905702',
    projectId: 'chat-app-fa80b',
    storageBucket: 'chat-app-fa80b.appspot.com',
    iosClientId: '468087905702-k0qu642gvab68iru5j3oal398nlnasah.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
